{
  "uid" : "8d05729e78719ca7",
  "name" : "test__list_data",
  "fullName" : "test.conduit_panniangyan_test.TestConduit#test__list_data",
  "historyId" : "db138463b55a4b656f3c8ccdeb27f523",
  "time" : {
    "start" : 1627899220784,
    "stop" : 1627899220784,
    "duration" : 0
  },
  "status" : "broken",
  "statusMessage" : "TypeError: setup() takes 0 positional arguments but 1 was given",
  "statusTrace" : "cls = <class '_pytest.runner.CallInfo'>\nfunc = <function call_runtest_hook.<locals>.<lambda> at 0x7f6d10ec0310>\nwhen = 'setup'\nreraise = (<class '_pytest.outcomes.Exit'>, <class 'KeyboardInterrupt'>)\n\n    @classmethod\n    def from_call(\n        cls,\n        func: \"Callable[[], TResult]\",\n        when: \"Literal['collect', 'setup', 'call', 'teardown']\",\n        reraise: Optional[\n            Union[Type[BaseException], Tuple[Type[BaseException], ...]]\n        ] = None,\n    ) -> \"CallInfo[TResult]\":\n        excinfo = None\n        start = timing.time()\n        precise_start = timing.perf_counter()\n        try:\n>           result: Optional[TResult] = func()\n\n/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/_pytest/runner.py:311: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/_pytest/runner.py:255: in <lambda>\n    lambda: ihook(item=item, **kwds), when=when, reraise=reraise\n/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/pluggy/hooks.py:286: in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\n/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/pluggy/manager.py:93: in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\n/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/pluggy/manager.py:84: in <lambda>\n    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(\n/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/_pytest/nose.py:13: in pytest_runtest_setup\n    call_optional(item.parent.obj, \"setup\")\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nobj = <conduit_panniangyan_test.TestConduit object at 0x7f6d1154afa0>\nname = 'setup'\n\n    def call_optional(obj, name):\n        method = getattr(obj, name, None)\n        isfixture = hasattr(method, \"_pytestfixturefunction\")\n        if method is not None and not isfixture and callable(method):\n            # If there's any problems allow the exception to raise rather than\n            # silently ignoring them.\n>           method()\nE           TypeError: setup() takes 0 positional arguments but 1 was given\n\n/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/_pytest/nose.py:38: TypeError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "parentSuite",
    "value" : "test"
  }, {
    "name" : "suite",
    "value" : "conduit_panniangyan_test"
  }, {
    "name" : "subSuite",
    "value" : "TestConduit"
  }, {
    "name" : "host",
    "value" : "fv-az77-41"
  }, {
    "name" : "thread",
    "value" : "3901-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "test.conduit_panniangyan_test"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 16,
        "skipped" : 0,
        "passed" : 0,
        "unknown" : 0,
        "total" : 16
      },
      "items" : [ {
        "uid" : "489b062d92eb3d23",
        "reportUrl" : "https://panniangyan.github.io/conduit/18//#testresult/489b062d92eb3d23",
        "status" : "broken",
        "statusDetails" : "TypeError: setup() takes 0 positional arguments but 1 was given",
        "time" : {
          "start" : 1627898435371,
          "stop" : 1627898435371,
          "duration" : 0
        }
      }, {
        "uid" : "f68bdc0dd7084177",
        "reportUrl" : "https://panniangyan.github.io/conduit/17//#testresult/f68bdc0dd7084177",
        "status" : "broken",
        "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=52653): Max retries exceeded with url: /session/f04a3cdd168c74da301d0c38b9cb3db9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca1c1a2370>: Failed to establish a new connection: [Errno 111] Connection refused'))",
        "time" : {
          "start" : 1627896378951,
          "stop" : 1627896378951,
          "duration" : 0
        }
      }, {
        "uid" : "a674b145b099b9ed",
        "reportUrl" : "https://panniangyan.github.io/conduit/16//#testresult/a674b145b099b9ed",
        "status" : "broken",
        "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=60017): Max retries exceeded with url: /session/b1a5c94c7bc7022ef76dd2ebb8ba0f70/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1a7501d0d0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
        "time" : {
          "start" : 1627895212530,
          "stop" : 1627895212530,
          "duration" : 0
        }
      }, {
        "uid" : "1a855daf79c1b31a",
        "reportUrl" : "https://panniangyan.github.io/conduit/15//#testresult/1a855daf79c1b31a",
        "status" : "broken",
        "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=43719): Max retries exceeded with url: /session/91742e4ead70df7aa6cbcad06f4f1bd2/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe18d1ab5e0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
        "time" : {
          "start" : 1627892996070,
          "stop" : 1627892996070,
          "duration" : 0
        }
      }, {
        "uid" : "73d7128bc4c31ed3",
        "reportUrl" : "https://panniangyan.github.io/conduit/14//#testresult/73d7128bc4c31ed3",
        "status" : "broken",
        "statusDetails" : "AttributeError: 'WebDriver' object has no attribute 'webdriver'",
        "time" : {
          "start" : 1627892617367,
          "stop" : 1627892617367,
          "duration" : 0
        }
      }, {
        "uid" : "435f4d0af8c95605",
        "reportUrl" : "https://panniangyan.github.io/conduit/12//#testresult/435f4d0af8c95605",
        "status" : "broken",
        "statusDetails" : "AttributeError: 'TestConduit' object has no attribute 'browser'",
        "time" : {
          "start" : 1627888455632,
          "stop" : 1627888455632,
          "duration" : 0
        }
      }, {
        "uid" : "b171446535fa9383",
        "reportUrl" : "https://panniangyan.github.io/conduit/11//#testresult/b171446535fa9383",
        "status" : "broken",
        "statusDetails" : "AttributeError: 'TestConduit' object has no attribute 'browser'",
        "time" : {
          "start" : 1627829932561,
          "stop" : 1627829932561,
          "duration" : 0
        }
      }, {
        "uid" : "1c567d9bef8d189",
        "reportUrl" : "https://panniangyan.github.io/conduit/10//#testresult/1c567d9bef8d189",
        "status" : "broken",
        "statusDetails" : "AttributeError: 'TestConduit' object has no attribute 'browser'",
        "time" : {
          "start" : 1627829830041,
          "stop" : 1627829830041,
          "duration" : 0
        }
      }, {
        "uid" : "dde53fa7e9a60c3f",
        "reportUrl" : "https://panniangyan.github.io/conduit/9//#testresult/dde53fa7e9a60c3f",
        "status" : "broken",
        "statusDetails" : "AttributeError: 'TestConduit' object has no attribute 'browser'",
        "time" : {
          "start" : 1627829049986,
          "stop" : 1627829049986,
          "duration" : 0
        }
      }, {
        "uid" : "4b77d4276fd923c1",
        "reportUrl" : "https://panniangyan.github.io/conduit/8//#testresult/4b77d4276fd923c1",
        "status" : "broken",
        "statusDetails" : "AttributeError: 'TestConduit' object has no attribute 'browser'",
        "time" : {
          "start" : 1627828717732,
          "stop" : 1627828717732,
          "duration" : 0
        }
      }, {
        "uid" : "84eb5417b53aae45",
        "reportUrl" : "https://panniangyan.github.io/conduit/7//#testresult/84eb5417b53aae45",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)",
        "time" : {
          "start" : 1627828254853,
          "stop" : 1627828254853,
          "duration" : 0
        }
      }, {
        "uid" : "609efaba1a0f583d",
        "reportUrl" : "https://panniangyan.github.io/conduit/6//#testresult/609efaba1a0f583d",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)",
        "time" : {
          "start" : 1627827068087,
          "stop" : 1627827068087,
          "duration" : 0
        }
      }, {
        "uid" : "fdf6ec9fa232047",
        "reportUrl" : "https://panniangyan.github.io/conduit/5//#testresult/fdf6ec9fa232047",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)",
        "time" : {
          "start" : 1627819955059,
          "stop" : 1627819955059,
          "duration" : 0
        }
      }, {
        "uid" : "9f43047b5d9d9b14",
        "reportUrl" : "https://panniangyan.github.io/conduit/4//#testresult/9f43047b5d9d9b14",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)",
        "time" : {
          "start" : 1627818410319,
          "stop" : 1627818410319,
          "duration" : 0
        }
      }, {
        "uid" : "900524d67f6c3007",
        "reportUrl" : "https://panniangyan.github.io/conduit/3//#testresult/900524d67f6c3007",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)",
        "time" : {
          "start" : 1627818159998,
          "stop" : 1627818159998,
          "duration" : 0
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "8d05729e78719ca7.json",
  "parameterValues" : [ ]
}