{
  "uid" : "fcb47d475e673110",
  "name" : "test__save_data_to_file",
  "fullName" : "test.conduit_panniangyan_test.TestConduit#test__save_data_to_file",
  "historyId" : "7a313d2f474045d07a049c444a01446a",
  "time" : {
    "start" : 1627898435583,
    "stop" : 1627898435583,
    "duration" : 0
  },
  "status" : "broken",
  "statusMessage" : "TypeError: setup() takes 0 positional arguments but 1 was given",
  "statusTrace" : "cls = <class '_pytest.runner.CallInfo'>\nfunc = <function call_runtest_hook.<locals>.<lambda> at 0x7fa5fe164310>\nwhen = 'setup'\nreraise = (<class '_pytest.outcomes.Exit'>, <class 'KeyboardInterrupt'>)\n\n    @classmethod\n    def from_call(\n        cls,\n        func: \"Callable[[], TResult]\",\n        when: \"Literal['collect', 'setup', 'call', 'teardown']\",\n        reraise: Optional[\n            Union[Type[BaseException], Tuple[Type[BaseException], ...]]\n        ] = None,\n    ) -> \"CallInfo[TResult]\":\n        excinfo = None\n        start = timing.time()\n        precise_start = timing.perf_counter()\n        try:\n>           result: Optional[TResult] = func()\n\n/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/_pytest/runner.py:311: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/_pytest/runner.py:255: in <lambda>\n    lambda: ihook(item=item, **kwds), when=when, reraise=reraise\n/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/pluggy/hooks.py:286: in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\n/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/pluggy/manager.py:93: in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\n/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/pluggy/manager.py:84: in <lambda>\n    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(\n/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/_pytest/nose.py:13: in pytest_runtest_setup\n    call_optional(item.parent.obj, \"setup\")\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nobj = <conduit_panniangyan_test.TestConduit object at 0x7fa5fe7ecd30>\nname = 'setup'\n\n    def call_optional(obj, name):\n        method = getattr(obj, name, None)\n        isfixture = hasattr(method, \"_pytestfixturefunction\")\n        if method is not None and not isfixture and callable(method):\n            # If there's any problems allow the exception to raise rather than\n            # silently ignoring them.\n>           method()\nE           TypeError: setup() takes 0 positional arguments but 1 was given\n\n/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/_pytest/nose.py:38: TypeError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "parentSuite",
    "value" : "test"
  }, {
    "name" : "suite",
    "value" : "conduit_panniangyan_test"
  }, {
    "name" : "subSuite",
    "value" : "TestConduit"
  }, {
    "name" : "host",
    "value" : "fv-az74-587"
  }, {
    "name" : "thread",
    "value" : "3661-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "test.conduit_panniangyan_test"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 15,
        "skipped" : 0,
        "passed" : 0,
        "unknown" : 0,
        "total" : 15
      },
      "items" : [ {
        "uid" : "8a3c381370e71401",
        "reportUrl" : "https://panniangyan.github.io/conduit/17//#testresult/8a3c381370e71401",
        "status" : "broken",
        "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=52653): Max retries exceeded with url: /session/f04a3cdd168c74da301d0c38b9cb3db9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca1bed78e0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
        "time" : {
          "start" : 1627896380093,
          "stop" : 1627896380093,
          "duration" : 0
        }
      }, {
        "uid" : "4acd4a16b2de655c",
        "reportUrl" : "https://panniangyan.github.io/conduit/16//#testresult/4acd4a16b2de655c",
        "status" : "broken",
        "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=60017): Max retries exceeded with url: /session/b1a5c94c7bc7022ef76dd2ebb8ba0f70/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1a74f16970>: Failed to establish a new connection: [Errno 111] Connection refused'))",
        "time" : {
          "start" : 1627895213830,
          "stop" : 1627895213830,
          "duration" : 0
        }
      }, {
        "uid" : "a759537b1f5edb68",
        "reportUrl" : "https://panniangyan.github.io/conduit/15//#testresult/a759537b1f5edb68",
        "status" : "broken",
        "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=43719): Max retries exceeded with url: /session/91742e4ead70df7aa6cbcad06f4f1bd2/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe18d0195b0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
        "time" : {
          "start" : 1627892997235,
          "stop" : 1627892997235,
          "duration" : 0
        }
      }, {
        "uid" : "7e68dce34a522ffb",
        "reportUrl" : "https://panniangyan.github.io/conduit/14//#testresult/7e68dce34a522ffb",
        "status" : "broken",
        "statusDetails" : "AttributeError: 'WebDriver' object has no attribute 'webdriver'",
        "time" : {
          "start" : 1627892617406,
          "stop" : 1627892617406,
          "duration" : 0
        }
      }, {
        "uid" : "f42004c54e48845c",
        "reportUrl" : "https://panniangyan.github.io/conduit/12//#testresult/f42004c54e48845c",
        "status" : "broken",
        "statusDetails" : "AttributeError: 'TestConduit' object has no attribute 'browser'",
        "time" : {
          "start" : 1627888455674,
          "stop" : 1627888455674,
          "duration" : 0
        }
      }, {
        "uid" : "b41f67a4d48c1f83",
        "reportUrl" : "https://panniangyan.github.io/conduit/11//#testresult/b41f67a4d48c1f83",
        "status" : "broken",
        "statusDetails" : "AttributeError: 'TestConduit' object has no attribute 'browser'",
        "time" : {
          "start" : 1627829932608,
          "stop" : 1627829932608,
          "duration" : 0
        }
      }, {
        "uid" : "cf1eb99938a669f9",
        "reportUrl" : "https://panniangyan.github.io/conduit/10//#testresult/cf1eb99938a669f9",
        "status" : "broken",
        "statusDetails" : "AttributeError: 'TestConduit' object has no attribute 'browser'",
        "time" : {
          "start" : 1627829830094,
          "stop" : 1627829830094,
          "duration" : 0
        }
      }, {
        "uid" : "dd2ecdbcd8e59f0e",
        "reportUrl" : "https://panniangyan.github.io/conduit/9//#testresult/dd2ecdbcd8e59f0e",
        "status" : "broken",
        "statusDetails" : "AttributeError: 'TestConduit' object has no attribute 'browser'",
        "time" : {
          "start" : 1627829050026,
          "stop" : 1627829050026,
          "duration" : 0
        }
      }, {
        "uid" : "f733c95e68e62742",
        "reportUrl" : "https://panniangyan.github.io/conduit/8//#testresult/f733c95e68e62742",
        "status" : "broken",
        "statusDetails" : "AttributeError: 'TestConduit' object has no attribute 'browser'",
        "time" : {
          "start" : 1627828717771,
          "stop" : 1627828717771,
          "duration" : 0
        }
      }, {
        "uid" : "d25f9e6e98320fd3",
        "reportUrl" : "https://panniangyan.github.io/conduit/7//#testresult/d25f9e6e98320fd3",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)",
        "time" : {
          "start" : 1627828260903,
          "stop" : 1627828260903,
          "duration" : 0
        }
      }, {
        "uid" : "9e3fba6f8130309b",
        "reportUrl" : "https://panniangyan.github.io/conduit/6//#testresult/9e3fba6f8130309b",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)",
        "time" : {
          "start" : 1627827074072,
          "stop" : 1627827074072,
          "duration" : 0
        }
      }, {
        "uid" : "65f83409fbce0d85",
        "reportUrl" : "https://panniangyan.github.io/conduit/5//#testresult/65f83409fbce0d85",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)",
        "time" : {
          "start" : 1627819961121,
          "stop" : 1627819961121,
          "duration" : 0
        }
      }, {
        "uid" : "7cf649d7a47ed808",
        "reportUrl" : "https://panniangyan.github.io/conduit/4//#testresult/7cf649d7a47ed808",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)",
        "time" : {
          "start" : 1627818416426,
          "stop" : 1627818416426,
          "duration" : 0
        }
      }, {
        "uid" : "7fa22d85c45b3ef6",
        "reportUrl" : "https://panniangyan.github.io/conduit/3//#testresult/7fa22d85c45b3ef6",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)",
        "time" : {
          "start" : 1627818166032,
          "stop" : 1627818166032,
          "duration" : 0
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "fcb47d475e673110.json",
  "parameterValues" : [ ]
}